### ISSUE TITLE
Performance issues starting at 65.8 GB of data

### ISSUE THREAD

**Issue by DanielRuf** [nodejs/Gzemnid#30]
It seems the `meta` task gets slower and slower and after about 60GB it starts to come to a hault.
I use a normal HDD and Node.js 10.15.0. In this case I also saw that the `node` process loads a huge amount of data into the memory which seems to probably be some memory leak.

Is there some issue known?

**Comment by ChALkeR** [comment]
@DanielRuf Have you tried increasing `--max-old-space-size`?
E.g. `--max-old-space-size=2000` or higher.

**Comment by DanielRuf** [comment]
What exactly does `--max-old-space-size=2000` do? There is no direct info in the readme. Not sure if thus could help. This is the second HDD (different vendor and size) which gets very slow at around 60GB+ which is problematic.

I guess SSD is the only option here.

**Comment by DanielRuf** [comment]
What exactly does `--max-old-space-size=2000` do? There is no direct info in the readme. Not sure if this could help. This is the second HDD (different vendor and size) which gets very slow at around 60GB+ which is problematic.

I guess SSD is the only option here.

**Comment by ChALkeR** [comment]
@DanielRuf `max-old-space-size` is a documented v8 option:
```
$ node --v8-options | grep max-old
  --max-old-space-size (max size of the old space (in Mbytes))
```

That is under an assumption that the bottleneck is in memory (as it is for some tasks).

For `meta` task specifically, there should be no memory-related bottleneck, so I don't see why that affect things.

Which operating system and FS do you use?
I did test on SSD only, though.

**Comment by ChALkeR** [comment]
I could try to make a patch that groups packages by first two letters, that should reduce the number of files per a single dir.

**Comment by DanielRuf** [comment]
I use macOS 10.14.3 and last time I had thus issue the node process read almost the same size of data on evedy start after this sfarted happening.

I will try the v8 option but I guess this does not solve that the write rate of the disks (1 and 2 TB) is vedy low after this started happening (few KB per second, often no writes).

I tried APFS and exFAT and deactivated spotlight for the whole volume before doing anything.

**Comment by DanielRuf** [comment]
I will post a few more info later today.

**Comment by DanielRuf** [comment]
> How does the process memory usage look like?

At the end when this happened the "read bytes" of the node process of the `meta` task grew to the size of the current size of the pool directory (and higher).

Memory usage seemed to be normal afaik.

**Comment by DanielRuf** [comment]
> Probably too many files in one directory for the file systems and disks

This seems to be the main issue.
Could not even format the disk on macOS with too many files in the meta directory.

After manually deleting a few gigabyte data and a few thousand files I could format the disk.

**Comment by DanielRuf** [comment]
The current disk is formatted with exfat.

**Comment by DanielRuf** [comment]
I wonder what the suggested hardware setup is. Can you provide some advice @ChALkeR? Specific file system configurations, SSD instead of HDD and so on?
