### ISSUE TITLE
What is "search.code.sh"?

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/Gzemnid#31]
The prebuilt docs mention this tool but it doesn't seem to be anywhere.

Is it just an lz4 piped into grep?

**Comment by ChALkeR** [comment]
Yes, it's just lz4 piped into grep, a one-liner.

It's available here: https://gzemnid.nodejs.org/datasets/out.2019-01-28/

**Comment by ChALkeR** [comment]
Upd: sorry, I accidentally edited your comment instead of mine. I reverted the edit.

**Comment by ChALkeR** [comment]
Btw, do you want ssh access to gzemnid.nodejs.org?

**Comment by ChALkeR** [comment]
Fixed in 490694fdc12161937df72b456254084a49b5895f -- I imported those to the repo and added a brief readme,
